import { betaHIVESchema } from '../models/betaHIVE-selection.types';
import { storySchema } from '../models/battleHIVE.types';
import {
  CONTENT_WARNINGS,
  FEEDBACK_SUBMISSIONS,
  PROMPT_SELECTIONS,
} from './admin-constants';

export const BETAHIVE_SELECTIONS: betaHIVESchema[] = [
  {
    id: 1,
    name: 'Fantasy',
    imgSource: 'fantasy.png',
    description: 'Magic, dragons, and other fantastical elements.',
  },
  {
    id: 2,
    name: 'Horror',
    imgSource: 'horror.png',
    description: 'Scary stories that will keep you up at night.',
  },
  {
    id: 3,
    name: 'Sci-Fi',
    imgSource: 'sci-fi.png',
    description: 'Stories set in the future or in space.',
  },
  {
    id: 4,
    name: 'Mystery',
    imgSource: 'mystery.png',
    description: 'Puzzles and enigmas to solve.',
  },
  {
    id: 5,
    name: 'Romance',
    imgSource: 'romance.png',
    description: 'Love stories and romantic adventures.',
  },
  {
    id: 6,
    name: 'Historical Fiction',
    imgSource: 'non-fiction.png',
    description: 'Stories set in the past.',
  },
  {
    id: 7,
    name: 'Adventure',
    imgSource: 'adventure.png',
    description: 'Exciting journeys and daring escapades.',
  },
  {
    id: 8,
    name: 'Suspense',
    imgSource: 'suspense.png',
    description: 'Suspenseful and thrilling stories.',
  },
];

export const STORY_SUBMISSIONS: storySchema[] = [
  {
    id: 1,
    title: 'Story 1',
    author: 'Author 1',
    story:
      'Once upon a time...Story 1 tried with all its might but could barely get an itch into what it was doing. The end.',
    HIVE: BETAHIVE_SELECTIONS[0].name,
    prompts: [PROMPT_SELECTIONS[0].name, PROMPT_SELECTIONS[6].name],
    isContentSensitive: false,
    contentWarnings: ['None'],
    wordCount: 1000,
    characterCount: 5000,
    status: 'Submitted',
    feedback: [
      {
        feedback: FEEDBACK_SUBMISSIONS[0].feedback,
        isPublic: FEEDBACK_SUBMISSIONS[0].isPublic,
        isPositive: FEEDBACK_SUBMISSIONS[0].isPositive,
        isAnonymous: FEEDBACK_SUBMISSIONS[0].isAnonymous,
      },
      {
        feedback: FEEDBACK_SUBMISSIONS[1].feedback,
        isPublic: FEEDBACK_SUBMISSIONS[1].isPublic,
        isPositive: FEEDBACK_SUBMISSIONS[1].isPositive,
        isAnonymous: FEEDBACK_SUBMISSIONS[1].isAnonymous,
      },
      {
        feedback: FEEDBACK_SUBMISSIONS[2].feedback,
        isPublic: FEEDBACK_SUBMISSIONS[2].isPublic,
        isPositive: FEEDBACK_SUBMISSIONS[2].isPositive,
        isAnonymous: FEEDBACK_SUBMISSIONS[2].isAnonymous,
      },
    ],
    wins: 0,
    losses: 0,
  },
  {
    id: 2,
    title: 'Story 2',
    author: 'Author 2',
    story:
      'Once upon a time...Story 2 worked real hard and got mixed results. The end.',
    HIVE: BETAHIVE_SELECTIONS[0].name,
    prompts: [PROMPT_SELECTIONS[0].name, PROMPT_SELECTIONS[6].name],
    isContentSensitive: false,
    contentWarnings: ['None'],
    wordCount: 1000,
    characterCount: 5000,
    status: 'Submitted',
    feedback: [
      {
        feedback: FEEDBACK_SUBMISSIONS[3].feedback,
        isPublic: FEEDBACK_SUBMISSIONS[3].isPublic,
        isPositive: FEEDBACK_SUBMISSIONS[3].isPositive,
        isAnonymous: FEEDBACK_SUBMISSIONS[3].isAnonymous,
      },
      {
        feedback: FEEDBACK_SUBMISSIONS[4].feedback,
        isPublic: FEEDBACK_SUBMISSIONS[4].isPublic,
        isPositive: FEEDBACK_SUBMISSIONS[4].isPositive,
        isAnonymous: FEEDBACK_SUBMISSIONS[4].isAnonymous,
      },
      {
        feedback: FEEDBACK_SUBMISSIONS[5].feedback,
        isPublic: FEEDBACK_SUBMISSIONS[5].isPublic,
        isPositive: FEEDBACK_SUBMISSIONS[5].isPositive,
        isAnonymous: FEEDBACK_SUBMISSIONS[5].isAnonymous,
      },
    ],
    wins: 0,
    losses: 0,
  },
  {
    id: 3,
    title: 'Story 3',
    author: 'Author 3',
    story:
      'Once upon a time...Story 3 got high and mighty on its ego... barely getting anything across to anyone who dared read it. The end.',
    HIVE: BETAHIVE_SELECTIONS[4].name,
    prompts: [PROMPT_SELECTIONS[1].name, PROMPT_SELECTIONS[6].name],
    isContentSensitive: false,
    contentWarnings: ['None'],
    wordCount: 350,
    characterCount: 5000,
    status: 'Submitted',
    feedback: [
      {
        feedback: FEEDBACK_SUBMISSIONS[6].feedback,
        isPublic: FEEDBACK_SUBMISSIONS[6].isPublic,
        isPositive: FEEDBACK_SUBMISSIONS[6].isPositive,
        isAnonymous: FEEDBACK_SUBMISSIONS[6].isAnonymous,
      },
      {
        feedback: FEEDBACK_SUBMISSIONS[7].feedback,
        isPublic: FEEDBACK_SUBMISSIONS[7].isPublic,
        isPositive: FEEDBACK_SUBMISSIONS[7].isPositive,
        isAnonymous: FEEDBACK_SUBMISSIONS[7].isAnonymous,
      },
      {
        feedback: FEEDBACK_SUBMISSIONS[8].feedback,
        isPublic: FEEDBACK_SUBMISSIONS[8].isPublic,
        isPositive: FEEDBACK_SUBMISSIONS[8].isPositive,
        isAnonymous: FEEDBACK_SUBMISSIONS[8].isAnonymous,
      },
    ],
    wins: 0,
    losses: 0,
  },
  {
    id: 4,
    title: 'Story 4',
    author: 'Author 4',
    story:
      'Once upon a time...Story 4 decided to hire a professional at Disney to write their story. They won because as we know, capitalism cheats the system and allows anyone with enough money to buy their way into anything to win. The end.',
    HIVE: BETAHIVE_SELECTIONS[0].name,
    prompts: [PROMPT_SELECTIONS[4].name, PROMPT_SELECTIONS[9].name],
    isContentSensitive: true,
    contentWarnings: [CONTENT_WARNINGS[2].name, CONTENT_WARNINGS[3].name],
    wordCount: 350,
    characterCount: 5000,
    status: 'Submitted',
    feedback: [
      {
        feedback: FEEDBACK_SUBMISSIONS[9].feedback,
        isPublic: FEEDBACK_SUBMISSIONS[9].isPublic,
        isPositive: FEEDBACK_SUBMISSIONS[9].isPositive,
        isAnonymous: FEEDBACK_SUBMISSIONS[9].isAnonymous,
      },
      {
        feedback: FEEDBACK_SUBMISSIONS[10].feedback,
        isPublic: FEEDBACK_SUBMISSIONS[10].isPublic,
        isPositive: FEEDBACK_SUBMISSIONS[10].isPositive,
        isAnonymous: FEEDBACK_SUBMISSIONS[10].isAnonymous,
      },
      {
        feedback: FEEDBACK_SUBMISSIONS[11].feedback,
        isPublic: FEEDBACK_SUBMISSIONS[11].isPublic,
        isPositive: FEEDBACK_SUBMISSIONS[11].isPositive,
        isAnonymous: FEEDBACK_SUBMISSIONS[11].isAnonymous,
      },
    ],
    wins: 0,
    losses: 0,
  },
  {
    id: 5,
    title: 'Story 5',
    author: 'Author 5',
    story:
      'Once upon a time...Story 5 had an amazing plot twist that left everyone in awe. The end.',
    HIVE: BETAHIVE_SELECTIONS[1].name,
    prompts: [PROMPT_SELECTIONS[2].name, PROMPT_SELECTIONS[7].name],
    isContentSensitive: false,
    contentWarnings: ['None'],
    wordCount: 1200,
    characterCount: 6000,
    status: 'Submitted',
    feedback: [
      {
        feedback: FEEDBACK_SUBMISSIONS[12].feedback,
        isPublic: FEEDBACK_SUBMISSIONS[12].isPublic,
        isPositive: FEEDBACK_SUBMISSIONS[12].isPositive,
        isAnonymous: FEEDBACK_SUBMISSIONS[12].isAnonymous,
      },
      {
        feedback: FEEDBACK_SUBMISSIONS[13].feedback,
        isPublic: FEEDBACK_SUBMISSIONS[13].isPublic,
        isPositive: FEEDBACK_SUBMISSIONS[13].isPositive,
        isAnonymous: FEEDBACK_SUBMISSIONS[13].isAnonymous,
      },
      {
        feedback: FEEDBACK_SUBMISSIONS[14].feedback,
        isPublic: FEEDBACK_SUBMISSIONS[14].isPublic,
        isPositive: FEEDBACK_SUBMISSIONS[14].isPositive,
        isAnonymous: FEEDBACK_SUBMISSIONS[14].isAnonymous,
      },
    ],
    wins: 0,
    losses: 0,
  },
  {
    id: 6,
    title: 'Story 6',
    author: 'Author 6',
    story:
      'Once upon a time...Story 6 had great pacing throughout, but the ending was too abrupt. The end.',
    HIVE: BETAHIVE_SELECTIONS[2].name,
    prompts: [PROMPT_SELECTIONS[3].name, PROMPT_SELECTIONS[8].name],
    isContentSensitive: false,
    contentWarnings: ['None'],
    wordCount: 1100,
    characterCount: 5500,
    status: 'Submitted',
    feedback: [
      {
        feedback: FEEDBACK_SUBMISSIONS[15].feedback,
        isPublic: FEEDBACK_SUBMISSIONS[15].isPublic,
        isPositive: FEEDBACK_SUBMISSIONS[15].isPositive,
        isAnonymous: FEEDBACK_SUBMISSIONS[15].isAnonymous,
      },
      {
        feedback: FEEDBACK_SUBMISSIONS[16].feedback,
        isPublic: FEEDBACK_SUBMISSIONS[16].isPublic,
        isPositive: FEEDBACK_SUBMISSIONS[16].isPositive,
        isAnonymous: FEEDBACK_SUBMISSIONS[16].isAnonymous,
      },
      {
        feedback: FEEDBACK_SUBMISSIONS[17].feedback,
        isPublic: FEEDBACK_SUBMISSIONS[17].isPublic,
        isPositive: FEEDBACK_SUBMISSIONS[17].isPositive,
        isAnonymous: FEEDBACK_SUBMISSIONS[17].isAnonymous,
      },
    ],
    wins: 0,
    losses: 0,
  },
  {
    id: 7,
    title: 'Story 7',
    author: 'Author 7',
    story:
      'Once upon a time...Story 7 was very engaging, but needed more background information. The end.',
    HIVE: BETAHIVE_SELECTIONS[3].name,
    prompts: [PROMPT_SELECTIONS[4].name, PROMPT_SELECTIONS[5].name],
    isContentSensitive: false,
    contentWarnings: ['None'],
    wordCount: 1300,
    characterCount: 6500,
    status: 'Submitted',
    feedback: [
      {
        feedback: FEEDBACK_SUBMISSIONS[18].feedback,
        isPublic: FEEDBACK_SUBMISSIONS[18].isPublic,
        isPositive: FEEDBACK_SUBMISSIONS[18].isPositive,
        isAnonymous: FEEDBACK_SUBMISSIONS[18].isAnonymous,
      },
      {
        feedback: FEEDBACK_SUBMISSIONS[19].feedback,
        isPublic: FEEDBACK_SUBMISSIONS[19].isPublic,
        isPositive: FEEDBACK_SUBMISSIONS[19].isPositive,
        isAnonymous: FEEDBACK_SUBMISSIONS[19].isAnonymous,
      },
      {
        feedback: FEEDBACK_SUBMISSIONS[20].feedback,
        isPublic: FEEDBACK_SUBMISSIONS[20].isPublic,
        isPositive: FEEDBACK_SUBMISSIONS[20].isPositive,
        isAnonymous: FEEDBACK_SUBMISSIONS[20].isAnonymous,
      },
    ],
    wins: 0,
    losses: 0,
  },
  {
    id: 8,
    title: 'Story 8',
    author: 'Author 8',
    story:
      'Once upon a time...Story 8 had fantastic world-building, but the plot was hard to follow. The end.',
    HIVE: BETAHIVE_SELECTIONS[4].name,
    prompts: [PROMPT_SELECTIONS[5].name, PROMPT_SELECTIONS[9].name],
    isContentSensitive: false,
    contentWarnings: ['None'],
    wordCount: 1400,
    characterCount: 7000,
    status: 'Submitted',
    feedback: [
      {
        feedback: FEEDBACK_SUBMISSIONS[21].feedback,
        isPublic: FEEDBACK_SUBMISSIONS[21].isPublic,
        isPositive: FEEDBACK_SUBMISSIONS[21].isPositive,
        isAnonymous: FEEDBACK_SUBMISSIONS[21].isAnonymous,
      },
      {
        feedback: FEEDBACK_SUBMISSIONS[22].feedback,
        isPublic: FEEDBACK_SUBMISSIONS[22].isPublic,
        isPositive: FEEDBACK_SUBMISSIONS[22].isPositive,
        isAnonymous: FEEDBACK_SUBMISSIONS[22].isAnonymous,
      },
      {
        feedback: FEEDBACK_SUBMISSIONS[23].feedback,
        isPublic: FEEDBACK_SUBMISSIONS[23].isPublic,
        isPositive: FEEDBACK_SUBMISSIONS[23].isPositive,
        isAnonymous: FEEDBACK_SUBMISSIONS[23].isAnonymous,
      },
    ],
    wins: 0,
    losses: 0,
  },
  {
    id: 9,
    title: 'Story 9',
    author: 'Author 9',
    story:
      'Once upon a time...Story 9 had a thrilling adventure that kept everyone on the edge of their seats. The end.',
    HIVE: BETAHIVE_SELECTIONS[6].name,
    prompts: [PROMPT_SELECTIONS[1].name, PROMPT_SELECTIONS[4].name],
    isContentSensitive: false,
    contentWarnings: ['None'],
    wordCount: 1500,
    characterCount: 7500,
    status: 'Submitted',
    feedback: [
      {
        feedback: FEEDBACK_SUBMISSIONS[24].feedback,
        isPublic: FEEDBACK_SUBMISSIONS[24].isPublic,
        isPositive: FEEDBACK_SUBMISSIONS[24].isPositive,
        isAnonymous: FEEDBACK_SUBMISSIONS[24].isAnonymous,
      },
      {
        feedback: FEEDBACK_SUBMISSIONS[25].feedback,
        isPublic: FEEDBACK_SUBMISSIONS[25].isPublic,
        isPositive: FEEDBACK_SUBMISSIONS[25].isPositive,
        isAnonymous: FEEDBACK_SUBMISSIONS[25].isAnonymous,
      },
      {
        feedback: FEEDBACK_SUBMISSIONS[26].feedback,
        isPublic: FEEDBACK_SUBMISSIONS[26].isPublic,
        isPositive: FEEDBACK_SUBMISSIONS[26].isPositive,
        isAnonymous: FEEDBACK_SUBMISSIONS[26].isAnonymous,
      },
    ],
    wins: 0,
    losses: 0,
  },
  {
    id: 10,
    title: 'Story 10',
    author: 'Author 10',
    story:
      'Once upon a time...Story 10 had a suspenseful plot that kept everyone guessing until the very end. The end.',
    HIVE: BETAHIVE_SELECTIONS[7].name,
    prompts: [PROMPT_SELECTIONS[2].name, PROMPT_SELECTIONS[9].name],
    isContentSensitive: false,
    contentWarnings: ['None'],
    wordCount: 1600,
    characterCount: 8000,
    status: 'Submitted',
    feedback: [
      {
        feedback: FEEDBACK_SUBMISSIONS[27].feedback,
        isPublic: FEEDBACK_SUBMISSIONS[27].isPublic,
        isPositive: FEEDBACK_SUBMISSIONS[27].isPositive,
        isAnonymous: FEEDBACK_SUBMISSIONS[27].isAnonymous,
      },
      {
        feedback: FEEDBACK_SUBMISSIONS[28].feedback,
        isPublic: FEEDBACK_SUBMISSIONS[28].isPublic,
        isPositive: FEEDBACK_SUBMISSIONS[28].isPositive,
        isAnonymous: FEEDBACK_SUBMISSIONS[28].isAnonymous,
      },
      {
        feedback: FEEDBACK_SUBMISSIONS[29].feedback,
        isPublic: FEEDBACK_SUBMISSIONS[29].isPublic,
        isPositive: FEEDBACK_SUBMISSIONS[29].isPositive,
        isAnonymous: FEEDBACK_SUBMISSIONS[29].isAnonymous,
      },
    ],
    wins: 0,
    losses: 0,
  },
  {
    id: 11,
    title: 'Story 11',
    author: 'Author 11',
    story:
      "Once upon a time...Story 11 had a heartwarming romance that touched everyone's hearts. The end.",
    HIVE: BETAHIVE_SELECTIONS[4].name,
    prompts: [PROMPT_SELECTIONS[3].name, PROMPT_SELECTIONS[7].name],
    isContentSensitive: false,
    contentWarnings: ['None'],
    wordCount: 1700,
    characterCount: 8500,
    status: 'Submitted',
    feedback: [
      {
        feedback: FEEDBACK_SUBMISSIONS[30].feedback,
        isPublic: FEEDBACK_SUBMISSIONS[30].isPublic,
        isPositive: FEEDBACK_SUBMISSIONS[30].isPositive,
        isAnonymous: FEEDBACK_SUBMISSIONS[30].isAnonymous,
      },
      {
        feedback: FEEDBACK_SUBMISSIONS[31].feedback,
        isPublic: FEEDBACK_SUBMISSIONS[31].isPublic,
        isPositive: FEEDBACK_SUBMISSIONS[31].isPositive,
        isAnonymous: FEEDBACK_SUBMISSIONS[31].isAnonymous,
      },
      {
        feedback: FEEDBACK_SUBMISSIONS[32].feedback,
        isPublic: FEEDBACK_SUBMISSIONS[32].isPublic,
        isPositive: FEEDBACK_SUBMISSIONS[32].isPositive,
        isAnonymous: FEEDBACK_SUBMISSIONS[32].isAnonymous,
      },
    ],
    wins: 0,
    losses: 0,
  },
  {
    id: 12,
    title: 'Story 12',
    author: 'Author 12',
    story:
      'Once upon a time...Story 12 had a mysterious plot that kept everyone intrigued. The end.',
    HIVE: BETAHIVE_SELECTIONS[3].name,
    prompts: [PROMPT_SELECTIONS[4].name, PROMPT_SELECTIONS[6].name],
    isContentSensitive: false,
    contentWarnings: ['None'],
    wordCount: 1800,
    characterCount: 9000,
    status: 'Submitted',
    feedback: [
      {
        feedback: FEEDBACK_SUBMISSIONS[33].feedback,
        isPublic: FEEDBACK_SUBMISSIONS[33].isPublic,
        isPositive: FEEDBACK_SUBMISSIONS[33].isPositive,
        isAnonymous: FEEDBACK_SUBMISSIONS[33].isAnonymous,
      },
      {
        feedback: FEEDBACK_SUBMISSIONS[34].feedback,
        isPublic: FEEDBACK_SUBMISSIONS[34].isPublic,
        isPositive: FEEDBACK_SUBMISSIONS[34].isPositive,
        isAnonymous: FEEDBACK_SUBMISSIONS[34].isAnonymous,
      },
      {
        feedback: FEEDBACK_SUBMISSIONS[35].feedback,
        isPublic: FEEDBACK_SUBMISSIONS[35].isPublic,
        isPositive: FEEDBACK_SUBMISSIONS[35].isPositive,
        isAnonymous: FEEDBACK_SUBMISSIONS[35].isAnonymous,
      },
    ],
    wins: 0,
    losses: 0,
  },
];
